#!/bin/bash
cat << EOF
This totally harmless file (which literally just prints this message) was
downloaded by 'make setup' AFTER you had given it full root privleges.

Be assured:
	This is NOT a virus (or "malware") of ANY nature
	NOTHING of ANY risk at all has been done

Enjoy these articles:-
	https://research.swtch.com/xz-script
	https://www.microsoft.com/en-us/security/blog/2021/01/28/zinc-attacks-against-security-researchers/

This might give some people a heart attack:-
  EICAR: X5O!P%@AP[4\PZX54(P^)7CC)7}$EICAR-STANDARD-ANTIVIRUS-TEST-FILE!$H+H*
EOF
